<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'FRONTEND_FLASH_FAIL_CREATE' => 'Не удалось сохранить комментарий. Попробуйте пожалуйста еще раз!',
    'FRONTEND_FLASH_FAIL_DELETE' => 'Не удалось удалить комментарий. Попробуйте пожалуйста еще раз!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Не удалось обновить комментарий. Попробуйте пожалуйста еще раз!',
    'FRONTEND_FLASH_RECORD_NOT_FOUND' => 'Ошибка 404 - страница не найдена!',
    'ATTR_AUTHOR' => 'Автор',
    'ATTR_CONTENT' => 'Комментарий',
    'ATTR_CREATED' => 'Дата создания',
    'ATTR_ID' => 'ИД',
    'ATTR_MODEL' => 'Модель',
    'ATTR_MODEL_CLASS' => 'Класс модели',
    'ATTR_PARENT' => 'Родитель',
    'ATTR_STATUS' => 'Статус',
    'ATTR_UPDATED' => 'Дата обновления',
    'BACKEND_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Не удалось обновить комментарий. Попробуйте пожалуйста еще раз!',
    'BACKEND_INDEX_SUBTITLE' => 'Список комментариев',
    'BACKEND_INDEX_TITLE' => 'Комментарии',
    'BACKEND_PROMPT_MODEL_CLASS' => 'Выберите класс модели',
    'BACKEND_PROMPT_STATUS' => 'Выберите статус',
    'BACKEND_UPDATE_SUBMIT' => 'Обновить',
    'BACKEND_UPDATE_SUBTITLE' => 'Обновление комментария',
    'BACKEND_UPDATE_TITLE' => 'Комментарии',
    'ERROR_MSG_INVALID_MODEL_ID' => 'Неправильный ID модели',
    'FRONTEND_WIDGET_COMMENTS_DELETE' => 'Удалить',
    'FRONTEND_WIDGET_COMMENTS_DELETED_COMMENT_TEXT' => 'Комментарий был удалён',
    'FRONTEND_WIDGET_COMMENTS_DELETE_CONFIRMATION' => 'Вы уверены что хотите удалить этот комментарий?',
    'FRONTEND_WIDGET_COMMENTS_FORM_SUBMIT' => 'Опубликовать комментарий',
    'FRONTEND_WIDGET_COMMENTS_FORM_TITLE' => 'Оставить комментарий',
    'FRONTEND_WIDGET_COMMENTS_REPLY' => 'Ответить',
    'FRONTEND_WIDGET_COMMENTS_UPDATE' => 'Редактировать',
    'STATUS_ACTIVE' => 'Активен',
    'STATUS_BANNED' => 'Забанен',
    'STATUS_DELETED' => 'Удалён',
];
