<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_UPDATE_SUBTITLE' => 'Обновление модели',
    'BACKEND_UPDATE_TITLE' => 'Модели',
    'ATTR_CREATED' => 'Дата создания',
    'ATTR_ID' => 'ИД',
    'ATTR_NAME' => 'Модель',
    'ATTR_STATUS' => 'Стату',
    'ATTR_UPDATED' => 'Дата обновления',
    'BACKEND_CREATE_PLACEHOLDER_NAME' => 'vova07/blogs/models/Blog',
    'BACKEND_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_CREATE_SUBTITLE' => 'Создание модели',
    'BACKEND_CREATE_TITLE' => 'Модели',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Не удалось сохранить модель. Попробуйте пожалуйста еще раз!',
    'BACKEND_FLASH_FAIL_ADMIN_DISABLE' => 'Не удалось выключить модуль. Попробуйте пожалуйста еще раз!',
    'BACKEND_FLASH_FAIL_ADMIN_ENABLE' => 'Не удалось включить модуль. Попробуйте пожалуйста еще раз!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Не удалось обновить модель. Попробуйте пожалуйста еще раз!',
    'BACKEND_INDEX_MODULES_DISABLE_CONFIRMATION' => 'Все комментарии модуля будут удалены. Вы уверены что хотите отключить этот модуль?',
    'BACKEND_INDEX_MODULE_BLOGS' => 'Блоги',
    'BACKEND_INDEX_SUBTITLE' => 'Список моделей',
    'BACKEND_INDEX_TITLE' => 'Модели',
    'BACKEND_INDEX_TITLE_ENABLING' => 'Включить/Выключить комментарии для установленных модулей',
    'BACKEND_UPDATE_SUBMIT' => 'Обновить',
    'STATUS_DISABLED' => 'Отключён',
    'STATUS_ENABLED' => 'Включён',
];
