<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_UPDATE_SUBTITLE' => 'Model ändern',
    'BACKEND_UPDATE_TITLE' => 'Models',
    'ATTR_CREATED' => 'Created date',
    'ATTR_ID' => 'ID',
    'ATTR_NAME' => 'Model',
    'ATTR_STATUS' => 'Status',
    'ATTR_UPDATED' => 'Updated date',
    'BACKEND_CREATE_PLACEHOLDER_NAME' => 'vova07/blogs/models/Blog',
    'BACKEND_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_CREATE_SUBTITLE' => 'Model anlegen',
    'BACKEND_CREATE_TITLE' => 'Models',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Model wurde nicht angelegt. Bitte nochmals versuchen!',
    'BACKEND_FLASH_FAIL_ADMIN_DISABLE' => 'Module wurde nicht deaktiviert. Bitte nochmals versuchen!',
    'BACKEND_FLASH_FAIL_ADMIN_ENABLE' => 'Module wurde nicht aktiviert. Bitte nochmals versuchen!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Model wurde nicht geändert. Bitte nochmals versuchen!',
    'BACKEND_INDEX_MODULES_DISABLE_CONFIRMATION' => 'Kommentare aller Module werden gelöscht. Sind Sie sicher, das Module zu deaktivieren?',
    'BACKEND_INDEX_MODULE_BLOGS' => 'Blogs',
    'BACKEND_INDEX_SUBTITLE' => 'Model-Liste',
    'BACKEND_INDEX_TITLE' => 'Models',
    'BACKEND_INDEX_TITLE_ENABLING' => 'Aktiviere/Deaktiviere Kommentare für installierte Module',
    'BACKEND_UPDATE_SUBMIT' => 'Ändern',
    'STATUS_DISABLED' => 'Deaktiviert',
    'STATUS_ENABLED' => 'Aktiviert',
];
