<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'FRONTEND_FLASH_FAIL_CREATE' => 'Kommentar wurde nicht gespeichert. Bitte nochmals versuchen!',
    'FRONTEND_FLASH_FAIL_DELETE' => 'Kommentar wurde nicht gelöscht. Bitte nochmals versuchen!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Kommentar wurde nicht geändert. Bitte nochmals versuchen!',
    'FRONTEND_FLASH_RECORD_NOT_FOUND' => 'Error 404 - page not found!',
    'ATTR_AUTHOR' => 'Author',
    'ATTR_CONTENT' => 'Kommentar',
    'ATTR_CREATED' => 'Created date',
    'ATTR_ID' => 'ID',
    'ATTR_MODEL' => 'Model',
    'ATTR_MODEL_CLASS' => 'Model class',
    'ATTR_PARENT' => 'Elternobjekt',
    'ATTR_STATUS' => 'Status',
    'ATTR_UPDATED' => 'Updated date',
    'BACKEND_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Kommentar wurde nicht geändert. Bitte nochmals versuchen!',
    'BACKEND_INDEX_SUBTITLE' => 'Kommentar-Liste',
    'BACKEND_INDEX_TITLE' => 'Kommentare',
    'BACKEND_PROMPT_MODEL_CLASS' => 'Wähle eine Model class',
    'BACKEND_PROMPT_STATUS' => 'Wähle einen Status',
    'BACKEND_UPDATE_SUBMIT' => 'Ändern',
    'BACKEND_UPDATE_SUBTITLE' => 'Kommentar ändern',
    'BACKEND_UPDATE_TITLE' => 'Kommentare',
    'ERROR_MSG_INVALID_MODEL_ID' => 'Ungültige Model ID',
    'FRONTEND_WIDGET_COMMENTS_DELETE' => 'Löschen',
    'FRONTEND_WIDGET_COMMENTS_DELETED_COMMENT_TEXT' => 'Kommentar wurde gelöscht.',
    'FRONTEND_WIDGET_COMMENTS_DELETE_CONFIRMATION' => 'Wollen Sie diesen Kommentar wirklich löschen?',
    'FRONTEND_WIDGET_COMMENTS_FORM_SUBMIT' => 'Submit comment',
    'FRONTEND_WIDGET_COMMENTS_FORM_TITLE' => 'Leave a comment',
    'FRONTEND_WIDGET_COMMENTS_REPLY' => 'Antworten',
    'FRONTEND_WIDGET_COMMENTS_UPDATE' => 'Editieren',
    'STATUS_ACTIVE' => 'Aktiv',
    'STATUS_BANNED' => 'Verbannt',
    'STATUS_DELETED' => 'Gelöscht',
];
