<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'BACKEND_UPDATE_SUBTITLE' => 'Model updating',
    'BACKEND_UPDATE_TITLE' => 'Models',
    'ATTR_CREATED' => 'Created date',
    'ATTR_ID' => 'ID',
    'ATTR_NAME' => 'Model',
    'ATTR_STATUS' => 'Status',
    'ATTR_UPDATED' => 'Updated date',
    'BACKEND_CREATE_PLACEHOLDER_NAME' => 'vova07/blogs/models/Blog',
    'BACKEND_CREATE_SUBMIT' => 'Save',
    'BACKEND_CREATE_SUBTITLE' => 'Model creating',
    'BACKEND_CREATE_TITLE' => 'Models',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Model has not been saved. Please try again!',
    'BACKEND_FLASH_FAIL_ADMIN_DISABLE' => 'Module has not been disabled. Please try again!',
    'BACKEND_FLASH_FAIL_ADMIN_ENABLE' => 'Module has not been enabled. Please try again!',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Model has not been updated. Please try again!',
    'BACKEND_INDEX_MODULES_DISABLE_CONFIRMATION' => 'All module\'s comments will be removed. Are you sure you want to disable this module?',
    'BACKEND_INDEX_MODULE_BLOGS' => 'Blogs',
    'BACKEND_INDEX_SUBTITLE' => 'Models list',
    'BACKEND_INDEX_TITLE' => 'Models',
    'BACKEND_INDEX_TITLE_ENABLING' => 'Enable/Disable comments for installed modules',
    'BACKEND_UPDATE_SUBMIT' => 'Update',
    'STATUS_DISABLED' => 'Disabled',
    'STATUS_ENABLED' => 'Enabled',
];
