<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'FRONTEND_FLASH_FAIL_CREATE' => 'Comment has not been saved. Please try again!',
    'FRONTEND_FLASH_FAIL_DELETE' => 'Comment has not been deleted. Please try again!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Comment has not been updated. Please try again!',
    'FRONTEND_FLASH_RECORD_NOT_FOUND' => 'Error 404 - page not found!',
    'ATTR_AUTHOR' => 'Author',
    'ATTR_CONTENT' => 'Comment',
    'ATTR_CREATED' => 'Created date',
    'ATTR_ID' => 'ID',
    'ATTR_MODEL' => 'Model',
    'ATTR_MODEL_CLASS' => 'Model class',
    'ATTR_PARENT' => 'Parent',
    'ATTR_STATUS' => 'Status',
    'ATTR_UPDATED' => 'Updated date',
    'BACKEND_CREATE_SUBMIT' => 'Save',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Comment has not been updated. Please try again!',
    'BACKEND_INDEX_SUBTITLE' => 'Comments list',
    'BACKEND_INDEX_TITLE' => 'Comments',
    'BACKEND_PROMPT_MODEL_CLASS' => 'Choose a model class',
    'BACKEND_PROMPT_STATUS' => 'Choose a status',
    'BACKEND_UPDATE_SUBMIT' => 'Update',
    'BACKEND_UPDATE_SUBTITLE' => 'Comment updating',
    'BACKEND_UPDATE_TITLE' => 'Comments',
    'ERROR_MSG_INVALID_MODEL_ID' => 'Invalid model ID',
    'FRONTEND_WIDGET_COMMENTS_DELETE' => 'Delete',
    'FRONTEND_WIDGET_COMMENTS_DELETED_COMMENT_TEXT' => 'Comment was deleted.',
    'FRONTEND_WIDGET_COMMENTS_DELETE_CONFIRMATION' => 'Are you sure you want to delete this comment?',
    'FRONTEND_WIDGET_COMMENTS_FORM_SUBMIT' => 'Submit Comment',
    'FRONTEND_WIDGET_COMMENTS_FORM_TITLE' => 'Leave a comment',
    'FRONTEND_WIDGET_COMMENTS_REPLY' => 'Reply',
    'FRONTEND_WIDGET_COMMENTS_UPDATE' => 'Edit',
    'STATUS_ACTIVE' => 'Active',
    'STATUS_BANNED' => 'Banned',
    'STATUS_DELETED' => 'Deleted',
];
