<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'FRONTEND_FLASH_FAIL_CREATE' => 'Comentário não foi salvo. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_DELETE' => 'Comentário não foi excluído. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Comentário não foi atualizado. Por favor tente novamente!',
    'FRONTEND_FLASH_RECORD_NOT_FOUND' => 'Erro 404 - página não encontrada!',
    'ATTR_AUTHOR' => 'Autor',
    'ATTR_CONTENT' => 'Comentário',
    'ATTR_CREATED' => 'Criado em',
    'ATTR_ID' => 'ID',
    'ATTR_MODEL' => 'Model',
    'ATTR_MODEL_CLASS' => 'Model class',
    'ATTR_PARENT' => 'Pai',
    'ATTR_STATUS' => 'Status',
    'ATTR_UPDATED' => 'Atualizado em',
    'BACKEND_CREATE_SUBMIT' => 'Salvar',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Comentário não foi excluído. Por favor tente novamente!',
    'BACKEND_INDEX_SUBTITLE' => 'Lista de comentários',
    'BACKEND_INDEX_TITLE' => 'Comentários',
    'BACKEND_PROMPT_MODEL_CLASS' => 'Escolher uma "model class"',
    'BACKEND_PROMPT_STATUS' => 'Escolher um status',
    'BACKEND_UPDATE_SUBMIT' => 'Atualizar',
    'BACKEND_UPDATE_SUBTITLE' => 'Atualizando comentário',
    'BACKEND_UPDATE_TITLE' => 'Comentários',
    'ERROR_MSG_INVALID_MODEL_ID' => 'Model ID inválido',
    'FRONTEND_WIDGET_COMMENTS_DELETE' => 'Deletar',
    'FRONTEND_WIDGET_COMMENTS_DELETED_COMMENT_TEXT' => 'Comentário foi excluído.',
    'FRONTEND_WIDGET_COMMENTS_DELETE_CONFIRMATION' => 'Tem certeza que deseja excluir este comentário?',
    'FRONTEND_WIDGET_COMMENTS_FORM_SUBMIT' => 'Enviar comentário',
    'FRONTEND_WIDGET_COMMENTS_FORM_TITLE' => 'Deixe um comentário',
    'FRONTEND_WIDGET_COMMENTS_REPLY' => 'Responder',
    'FRONTEND_WIDGET_COMMENTS_UPDATE' => 'Editar',
    'STATUS_ACTIVE' => 'Ativo',
    'STATUS_BANNED' => 'Banido',
    'STATUS_DELETED' => 'Excluído',
];
