<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'BACKEND_UPDATE_SUBTITLE' => 'Atualizando model',
	'BACKEND_UPDATE_TITLE' => 'Models',
	'ATTR_CREATED' => 'Criado em',
	'ATTR_ID' => 'ID',
	'ATTR_NAME' => 'Model',
	'ATTR_STATUS' => 'Status',
	'ATTR_UPDATED' => 'Atualizado em',
	'BACKEND_CREATE_PLACEHOLDER_NAME' => 'vova07/blogs/models/Blog',
	'BACKEND_CREATE_SUBMIT' => 'Salvar',
	'BACKEND_CREATE_SUBTITLE' => 'Criando model',
	'BACKEND_CREATE_TITLE' => 'Models',
	'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Model não foi salvo. Por favor tente novamente!',
	'BACKEND_FLASH_FAIL_ADMIN_DISABLE' => 'Model não foi desabilitado. Por favor tente novamente!',
	'BACKEND_FLASH_FAIL_ADMIN_ENABLE' => 'Model não foi habilitado. Por favor tente novamente!',
	'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => 'Model não foi atualizado. Por favor tente novamente!',
	'BACKEND_INDEX_MODULES_DISABLE_CONFIRMATION' => 'Todos os registros do módulo serão removidos. Tem certeza que deseja desabilitar este módulo?',
	'BACKEND_INDEX_MODULE_BLOGS' => 'Blogs',
	'BACKEND_INDEX_SUBTITLE' => 'Lista de models',
	'BACKEND_INDEX_TITLE' => 'Models',
	'BACKEND_INDEX_TITLE_ENABLING' => 'Habilitar/Desabilitar comentários para o módulo instalado',
	'BACKEND_UPDATE_SUBMIT' => 'Atualizar',
	'STATUS_DISABLED' => 'Desativar',
	'STATUS_ENABLED' => 'Ativar',
];
